# Configs of everything
---
# --------------- DB Server Related -----------------
# 0-chengKV, 1-google, 2-rocks, 3-postgres, 5-Tapir, 6-CockroachDB, 7-YugaByteDB, 8-TiDB, 9-SQLServer, 10-H2
LIB_TYPE: 3

DB_URL: "jdbc:mysql://127.0.0.1:5432/postgres"

# ---------------- Client library -------------------
USE_INSTRUMENT: true  # ??
NUM_TXN_IN_ENTITY: 1
MAX_FZ_TXN_NUM: 20

#USE_NEW_EPOCH_TXN: false
TIMESTAMP_ON: false
LOCAL_LOG: true
LOCAL_REMOTE_LOG: false
CLOUD_LOG: false
SIGN_DATA: false

RESULT_FILE_NAME: /tmp/viper/result.txt
COBRA_FD: /tmp/viper/
# ------------------ RPC related --------------------
SERVER_HOST: ye-cheng.duckdns.org
# SERVER_HOST: 172.17.0.1
SERVER_PORT: 8980

# ----------------- benchmark related ---------------
# 0-CHENG, 1-TPCC, 2-YCSB, 3-RUBIS, 4-TWITTER
BENCH_TYPE: 0

# simply skip the data loading or testing process
SKIP_LOADING: false
SKIP_TESTING: false
# set this to true: loading period will only store pure value,
# when those records are read from DB, they are given txnID/writeID: 0xbebeebee
DONT_RECORD_LOADING: true
REDIS_ADDRESS: "redis://10.200.205.118/0"

TXN_NUM: 1000
THREAD_NUM: 24
CLIENT_NUM: 1
# slow run: sleep this amount of milliseconds after sending every THROUGHPUT_PER_WAIT transaction
WAIT_BETWEEN_TXNS: 0
THROUGHPUT_PER_WAIT: 1000
# this ID should be globally unique
CLIENT_ID: 1

# remote log through sockets
VERIFIER_HOSTNAME: localhost


# ----------------- chengTxn related ----------------
# txn and op
OP_PER_CHENGTXN: 8
# ------------- chengTxn/YCSBT related --------------
SEED: 123123123
NUM_KEYS: 10000
RATIO_INSERT: 20
#RATIO_RANGEINSERT: 0
RATIO_READ: 20
RATIO_UPDATE: 20
RATIO_DELETE: 20
#RATIO_RANGEDELETE: 0
RATIO_RMW: 0
RATIO_RANGE: 20
# --------------------TPC-C related------------------
WAREHOUSE_NUM: 1
# ---------------------RUBIS related-----------------
RUBIS_USERS_NUM: 20000
# ------------------- TWITTER related----------------
TWITTER_USERS_NUM: 1000

# ------------------- YugaByteDB related----------------
YUGABYTE_PASSWORD: ""
YUGABYTE_DB_URLS: ["34.152.4.39"]
YUGABYTE_PORTS: [5433]
YUGABYTE_USERNAME: yugabyte
YUGABYTE_DATABASE_NAME: yugabyte

# ------------------- TiDB related----------------
#TIDB_PASSWORD: ""
#TIDB_DB_URLS: [""]
#TIDB_PORTS: [4000]
#TIDB_USERNAME: root
#TIDB_DATABASE_NAME: mys
TIDB_PASSWORD: "viper321"
TIDB_DB_URLS: ["34.148.93.160", "34.74.141.161", "34.74.141.161"]
TIDB_PORTS: [4000, 4000, 4000]
TIDB_USERNAME: root
TIDB_DATABASE_NAME: 

# ------------------- PostgreSQL related----------------
PG_PASSWORD: "password"
PG_DB_HOSTS: ["localhost"]
PG_PORTS: [5432]
PG_USERNAME: postgres
PG_DATABASE_NAME: postgres

# ------------------ h2 related -------------------------
H2_PASSWORD: ""
H2_DB_URLS: ["34.148.93.160"]
H2_PORTS: [9092]
H2_USERNAME: sa
H2_DATABASE_NAME: test2

# ------------------- ISOLATION LEVEL related----------------
# 1: SERIALIZABLE, 2: SNAPSHOT ISOLATION
ISOLATION_LEVEL: 2

# string key or integer key? 0-string, 1-integer
KEY_TYPE: 1

#
TAG: "normal"
#TAG: "RM"
#TAG: "WM"